(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{

/***/ "./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js!./node_modules/vue-markdown-loader/lib/markdown-compiler.js?!./packages/cropper/zh-CN.md?vue&type=script&lang=js&":
/*!********************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/babel-loader/lib??ref--1!./node_modules/vue-loader/lib!./node_modules/vue-markdown-loader/lib/markdown-compiler.js??ref--8-1!./packages/cropper/zh-CN.md?vue&type=script&lang=js& ***!
  \********************************************************************************************************************************************************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n/* harmony default export */ __webpack_exports__[\"default\"] = ({\n  data: function data() {\n    return {\n      defaultImgSrc: 'https://fengyuanchen.github.io/cropperjs/images/picture.jpg',\n      // 静态图片\n      imgSrc: '',\n      // 上传的图片地址\n      cropImg: '',\n      // 裁剪后的图片地址\n      imgStyle: {\n        width: '500px',\n        height: '315px'\n      },\n      viewMode: 1,\n      movable: false,\n      rotatable: false,\n      zoomable: false,\n      zoomOnTouch: false,\n      zoomOnWheel: false,\n      autoCropArea: 0.9,\n      minCropWidth: 400,\n      minCropHeight: 300,\n      aspectRatio: (this.minCropWidth || 400) / (this.minCropHeight || 300),\n      minDropBoxWidth: this.minCropWidth,\n      minDropBoxHeight: this.minCropHeight\n    };\n  },\n  methods: {\n    setImage: function setImage(e) {\n      var _this = this;\n\n      var file = e.target.files[0];\n\n      if (!file.type.includes('image/')) {\n        this.$message.warning('请上传图片');\n        return;\n      }\n\n      if (typeof FileReader === 'function') {\n        var reader = new FileReader();\n\n        reader.onload = function (event) {\n          _this.imgSrc = event.target.result; // rebuild cropperjs with the updated source\n\n          _this.$refs.cropper.replace(event.target.result);\n\n          _this.initCropImg();\n        };\n\n        reader.readAsDataURL(file);\n      } else {\n        this.$message.error('您的浏览器太旧了，请升级到最新版本的Chrome浏览器再来操作');\n      }\n    },\n    initCropImg: function initCropImg() {\n      var canvasWidth = this.$refs.cropper.offsetWidth;\n      this.$refs.cropper.setCanvasData({\n        left: 0,\n        top: 0,\n        width: canvasWidth\n      });\n      this.$refs.cropper.setCropBoxData({\n        left: 0,\n        top: 0,\n        width: 400,\n        height: 300\n      });\n    },\n    cropImage: function cropImage() {\n      this.cropImg = this.$refs.cropper.getCroppedCanvas().toDataURL();\n    },\n    rotate: function rotate() {\n      this.$refs.cropper.rotate(90);\n    },\n    zoom: function zoom(ratio) {\n      this.$refs.cropper.relativeZoom(ratio);\n    },\n    enable: function enable() {\n      this.$refs.cropper.enable();\n    },\n    disable: function disable() {\n      this.$refs.cropper.disable();\n    },\n    reset: function reset() {\n      this.$refs.cropper.reset();\n    },\n    destroyCropImg: function destroyCropImg() {\n      this.$refs.cropper.destroy();\n    }\n  }\n});\n\n//# sourceURL=webpack:///./packages/cropper/zh-CN.md?./node_modules/babel-loader/lib??ref--1!./node_modules/vue-loader/lib!./node_modules/vue-markdown-loader/lib/markdown-compiler.js??ref--8-1");

/***/ }),

/***/ "./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js!./node_modules/vue-markdown-loader/lib/markdown-compiler.js?!./packages/cropper/zh-CN.md?vue&type=template&id=97cddf7e&":
/*!**************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib!./node_modules/vue-markdown-loader/lib/markdown-compiler.js??ref--8-1!./packages/cropper/zh-CN.md?vue&type=template&id=97cddf7e& ***!
  \**************************************************************************************************************************************************************************************************************************************************/
/*! exports provided: render, staticRenderFns */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"render\", function() { return render; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"staticRenderFns\", function() { return staticRenderFns; });\nvar render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('section',[_c('h2',[_vm._v(\"Cropper 图片裁剪器\")]),_vm._v(\" \"),_c('h3',[_vm._v(\"代码示例\")]),_vm._v(\" \"),_c('h4',[_vm._v(\"基本使用\")]),_vm._v(\" \"),_c('div',{staticClass:\"demo-block\"},[_c('input',{staticStyle:{\"font-size\":\"1.2em\",\"padding\":\"10px 0\"},attrs:{\"type\":\"file\",\"name\":\"image\",\"accept\":\"image/*\"},on:{\"change\":_vm.setImage}}),_vm._v(\" \"),_c('hr'),_vm._v(\" \"),_c('div',{staticClass:\"demo-cropper\",staticStyle:{\"width\":\"500px\",\"height\":\"315px\",\"border\":\"1px solid gray\",\"display\":\"inline-block\"}},[_c('mi-cropper',{ref:\"cropper\",attrs:{\"src\":_vm.imgSrc || _vm.defaultImgSrc,\"alt\":\"头像\",\"guides\":true,\"view-mode\":_vm.viewMode,\"auto-crop-area\":_vm.autoCropArea,\"drag-mode\":\"crop\",\"min-drop-box-width\":_vm.minDropBoxWidth,\"min-drop-box-height\":_vm.minDropBoxHeight,\"aspectRatio\":_vm.aspectRatio,\"movable\":_vm.movable,\"img-style\":_vm.imgStyle}})],1),_vm._v(\" \"),_c('img',{ref:\"cropImg\",staticStyle:{\"width\":\"200px\",\"height\":\"150px\",\"border\":\"1px solid gray\"},attrs:{\"src\":_vm.cropImg,\"id\":\"cropImg\",\"alt\":\"\"}}),_vm._v(\" \"),(_vm.imgSrc)?_c('div',[_c('el-button',{on:{\"click\":_vm.cropImage}},[_vm._v(\"裁剪图片\")]),_vm._v(\" \"),_c('el-button',{on:{\"click\":_vm.rotate}},[_vm._v(\"旋转图片90°\")]),_vm._v(\" \"),_c('el-button',{on:{\"click\":function () { return _vm.zoom(0.1); }}},[_vm._v(\"放大0.1\")]),_vm._v(\" \"),_c('el-button',{on:{\"click\":function () { return _vm.zoom(-0.1); }}},[_vm._v(\"缩小0.1\")]),_vm._v(\" \"),_c('el-button',{on:{\"click\":_vm.disable}},[_vm._v(\"锁定\")]),_vm._v(\" \"),_c('el-button',{on:{\"click\":_vm.enable}},[_vm._v(\"解锁\")]),_vm._v(\" \"),_c('el-button',{on:{\"click\":_vm.reset}},[_vm._v(\"重置\")]),_vm._v(\" \"),_c('el-button',{on:{\"click\":_vm.destroyCropImg}},[_vm._v(\"销毁\")])],1):_vm._e()])])}\nvar staticRenderFns = []\n\n\n\n//# sourceURL=webpack:///./packages/cropper/zh-CN.md?./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib!./node_modules/vue-markdown-loader/lib/markdown-compiler.js??ref--8-1");

/***/ }),

/***/ "./packages/cropper/zh-CN.md":
/*!***********************************!*\
  !*** ./packages/cropper/zh-CN.md ***!
  \***********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _zh_CN_md_vue_type_template_id_97cddf7e___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./zh-CN.md?vue&type=template&id=97cddf7e& */ \"./packages/cropper/zh-CN.md?vue&type=template&id=97cddf7e&\");\n/* harmony import */ var _zh_CN_md_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./zh-CN.md?vue&type=script&lang=js& */ \"./packages/cropper/zh-CN.md?vue&type=script&lang=js&\");\n/* empty/unused harmony star reexport *//* harmony import */ var _node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../node_modules/vue-loader/lib/runtime/componentNormalizer.js */ \"./node_modules/vue-loader/lib/runtime/componentNormalizer.js\");\n\n\n\n\n\n/* normalize component */\n\nvar component = Object(_node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_2__[\"default\"])(\n  _zh_CN_md_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_1__[\"default\"],\n  _zh_CN_md_vue_type_template_id_97cddf7e___WEBPACK_IMPORTED_MODULE_0__[\"render\"],\n  _zh_CN_md_vue_type_template_id_97cddf7e___WEBPACK_IMPORTED_MODULE_0__[\"staticRenderFns\"],\n  false,\n  null,\n  null,\n  null\n  \n)\n\ncomponent.options.__file = \"zh-CN.md\"\n/* harmony default export */ __webpack_exports__[\"default\"] = (component.exports);\n\n//# sourceURL=webpack:///./packages/cropper/zh-CN.md?");

/***/ }),

/***/ "./packages/cropper/zh-CN.md?vue&type=script&lang=js&":
/*!************************************************************!*\
  !*** ./packages/cropper/zh-CN.md?vue&type=script&lang=js& ***!
  \************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _node_modules_babel_loader_lib_index_js_ref_1_node_modules_vue_loader_lib_index_js_node_modules_vue_markdown_loader_lib_markdown_compiler_js_ref_8_1_zh_CN_md_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! -!../../node_modules/babel-loader/lib??ref--1!../../node_modules/vue-loader/lib!../../node_modules/vue-markdown-loader/lib/markdown-compiler.js??ref--8-1!./zh-CN.md?vue&type=script&lang=js& */ \"./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js!./node_modules/vue-markdown-loader/lib/markdown-compiler.js?!./packages/cropper/zh-CN.md?vue&type=script&lang=js&\");\n/* empty/unused harmony star reexport */ /* harmony default export */ __webpack_exports__[\"default\"] = (_node_modules_babel_loader_lib_index_js_ref_1_node_modules_vue_loader_lib_index_js_node_modules_vue_markdown_loader_lib_markdown_compiler_js_ref_8_1_zh_CN_md_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_0__[\"default\"]); \n\n//# sourceURL=webpack:///./packages/cropper/zh-CN.md?");

/***/ }),

/***/ "./packages/cropper/zh-CN.md?vue&type=template&id=97cddf7e&":
/*!******************************************************************!*\
  !*** ./packages/cropper/zh-CN.md?vue&type=template&id=97cddf7e& ***!
  \******************************************************************/
/*! exports provided: render, staticRenderFns */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_node_modules_vue_markdown_loader_lib_markdown_compiler_js_ref_8_1_zh_CN_md_vue_type_template_id_97cddf7e___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! -!../../node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!../../node_modules/vue-loader/lib!../../node_modules/vue-markdown-loader/lib/markdown-compiler.js??ref--8-1!./zh-CN.md?vue&type=template&id=97cddf7e& */ \"./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js!./node_modules/vue-markdown-loader/lib/markdown-compiler.js?!./packages/cropper/zh-CN.md?vue&type=template&id=97cddf7e&\");\n/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, \"render\", function() { return _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_node_modules_vue_markdown_loader_lib_markdown_compiler_js_ref_8_1_zh_CN_md_vue_type_template_id_97cddf7e___WEBPACK_IMPORTED_MODULE_0__[\"render\"]; });\n\n/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, \"staticRenderFns\", function() { return _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_node_modules_vue_markdown_loader_lib_markdown_compiler_js_ref_8_1_zh_CN_md_vue_type_template_id_97cddf7e___WEBPACK_IMPORTED_MODULE_0__[\"staticRenderFns\"]; });\n\n\n\n//# sourceURL=webpack:///./packages/cropper/zh-CN.md?");

/***/ })

}]);